### ISSUE TITLE
Uncaught Error: Assertion failed: Node.off was called but no listener was removed

### ISSUE THREAD

**Issue by samreid** [phetsims/models-of-the-hydrogen-atom#10]
During automated fuzz testing:

Error: Assertion failed: Node.off was called but no listener was removed
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:23:13)
    at Node.offOverride [as off] (http://localhost/scenery/js/nodes/Node.js?bust=1478379875452:4474:17)
    at Node.removeEventListener (http://localhost/scenery/js/nodes/Node.js?bust=1478379875452:4396:19)
    at SnapshotsDialog.Panel.disposePanel (http://localhost/sun/js/Panel.js?bust=1478379875452:128:17)
    at SnapshotsDialog.dispose (http://localhost/sun/js/Panel.js?bust=1478379875452:141:12)
    at SnapshotsDialog.dispose (http://localhost/models-of-the-hydrogen-atom/js/spectra/view/SnapshotsDialog.js?bust=1478379875452:86:60)
    at SnapshotsDialog.hide (http://localhost/models-of-the-hydrogen-atom/js/spectra/view/SnapshotsDialog.js?bust=1478379875452:91:12)
    at Array. (http://localhost/models-of-the-hydrogen-atom/js/spectra/view/SnapshotsDialog.js?bust=1478379875452:49:14)
    at Emitter.emit2 (http://localhost/axon/js/Emitter.js?bust=1478379875452:139:49)
    at NumberProperty._notifyObservers (http://localhost/axon/js/Property.js?bust=1478379875452:167:29)

**Comment by pixelzoom** [comment]
`SnapshotDialog` extends`Dialog`, which extends `Panel`.  This is a bug in `Panel.dispose`.  It's failing at Panel line 128:

```js
125 this.disposePanel = function() {
126   options.tandem && options.tandem.removeInstance( this );
127   if ( options.resize ) {
128      content.removeEventListener( 'bounds', updateBackground );
129   }
130 };
```

Dialog is (imo) in bad shape (see https://github.com/phetsims/joist/issues/359), not production code. And I don't have time to address this where it should be addressed (which is not in MOTHA).  So I'm going to comment out the dispose function in `SnapshotDialog`, and create yet-another issue indicating that Dialog.dispose is buggy.

**Comment by pixelzoom** [comment]
This was apparently caused by @7754d0a1ea95c345377edd200b32ccbd3ef74d95, and other sims are failing (e.g. rutherford-scattering, on start).

**Comment by pixelzoom** [comment]
Reopening, assigned to @andrewadare.

**Comment by pixelzoom** [comment]
@andrewadare Assign back to me when you've fixed Panel.dispose, and I'll restore the dispose call in SnapshotDialog.

**Comment by andrewadare** [comment]
As mentioned in https://github.com/phetsims/sun/issues/212#issuecomment-258968887, the problem was not with Panel.dispose (which was done correctly), it was that the new Panel.disposePanel() method was shadowed in Rutherford Scattering. There were a few red herrings in this thread, but I think everything is resolved: Rutherford starts without errors now (for me), and I'm unable to reproduce a reported problem with MOTHA in fuzz testing with `Dialog.prototype.dispose.call( this );` uncommented in SnapshotsDialog.js.

@pixelzoom can you confirm or falsify my findings?

**Comment by pixelzoom** [comment]
Rutherford Scattering is working fine.

MOTHA is still failing when SnapshotsDialog.dispose calls Dialog.dispose. Steps to reproduce:

1. start the sim
2. go to Spectra screen
3. click on green '+' button to expand Spectrometer accordion box
4. click on camera icon (lower right in Spectrometer accordion box)
5. click on "View snapshots" button
6. click anywhere outside the snapshots dialog to dismiss it
7. click on "View snapshots" button again
8. click on trash can icon in snapshots dialog, which causes assertion failure:

![screenshot_62](https://cloud.githubusercontent.com/assets/3046552/20077919/9f63716c-a4fb-11e6-9859-0fcd3e621f20.png)

That said... I don't know that you need to necessarily work on this.  It may be a problem that's still linger in Panel, or it may be something higher in the stack.

**Comment by andrewadare** [comment]
@pixelzoom did 7b2779e fix this? Following steps 1-8 exactly, I am unable to reproduce on master.

**Comment by andrewadare** [comment]
I see...I needed to uncomment `Dialog.prototype.dispose.call( this );` in SnapshotsDialog.js
